In [3]:
# Given arr = np.array([5, 10, 15]),  Add a scalar 2
import numpy as np
a = np.array([5, 10, 15])
result = a + 2 # adding the scalar
result

array([ 7, 12, 17])

In [4]:
# Subtract an array [1, 2, 3]
res = result - np.array([1, 2, 3])
res

array([ 6, 10, 14])

In [6]:
# Multiply by [2, 0, 1]
res1 = res * np.array([2, 0, 1])
res1

array([12,  0, 14])