In [1]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60])

In [4]:
# Get the first 3 elements
arr[0:3]

array([10, 20, 30])

In [6]:
# Get the last 2 elements
arr[4:6]

array([50, 60])

In [8]:
# Reverse the array
arr = np.array([10, 20, 30, 40, 50, 60])
reversed_arr = arr[::-1]
reversed_arr

array([60, 50, 40, 30, 20, 10])